spring:
  application:
    name : bucketstore

  datasource:
    mysql:
      jdbc-url: jdbc:mysql://172.16.73.2:3306/bucketstore
      username: bucketstore
      password: bucketstore
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    defaultModelsExpandDepth: 2
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

server:
  port: 8088