spring:
  application:
    name : bucketstore

  datasource:
    mysql:
      jdbc-url: jdbc:mysql://172.16.73.2:3306/bucketstore
      username: bucketstore
      password: bucketstore
      driver-class-name: com.mysql.cj.jdbc.Driver