spring:
  application:
    name : bucketstore

  datasource:
    mysql:
      jdbc-url: jdbc:mysql://172.16.73.2:3306/bucketstore
      username: bucketstore
      password: bucketstore
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8088