-- 사용자
INSERT INTO USERS (USER_ID, EMAIL, PASSWORD, NAME, PHONE_NUMBER, ADDRESS, ZIP_CODE, CREATED_AT, UPDATED_AT)
VALUES (1, 'test1@example.com', 'password', '홍길동', '01012345678', '서울시 강남구', '12345', NOW(), NOW());

-- 상품 (PRODUCT)
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, BASE_PRICE, BRAND, CATEGORY, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES
    (1, 'PROD001', '테스트 상품1', 1000, '브랜드1', '카테고리1', '설명1', NOW(), NOW()),
    (2, 'PROD002', '테스트 상품2', 2000, '브랜드2', '카테고리2', '설명2', NOW(), NOW());

-- 상품 옵션 (PRODUCT_OPTION)
INSERT INTO PRODUCT_OPTION (OPTION_ID, PRODUCT_ID, COLOR, SIZE, ADDITIONAL_PRICE, STOCK_QTY, BARCODE, CREATED_AT, UPDATED_AT)
VALUES
    (1, 1, 'Red', 'M', 0, 100, 'BAR001', NOW(), NOW()),
    (2, 2, 'Blue', 'L', 0, 100, 'BAR002', NOW(), NOW());

-- 주문 (ORDER)
-- INSERT INTO ORDERS (ORDER_ID, ORDER_CODE, USER_ID, ORDER_STATUS, TOTAL_PRICE, DELIVERY_FEE, ORDER_DATE, CREATED_AT, UPDATED_AT)
-- VALUES (1, 'ORDER001', 1, 'PENDING', 3000, 0, NOW(), NOW(), NOW());
--
-- -- 주문 아이템
-- INSERT INTO ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, OPTION_ID, QUANTITY, ITEM_PRICE, CREATED_AT, UPDATED_AT)
-- VALUES
--     (1, 1, 1, 1, 1, 1000, NOW(), NOW()),
--     (2, 1, 2, 2, 1, 2000, NOW(), NOW());